BloggerBlogBundle_homepage:
  pattern: /
  defaults: { _controller: BloggerBlogBundle:Page:index }
  requirements:
    _method: GET
    
BloggerBlogBundle_about:    
  pattern: /about
  defaults: { _controller: BloggerBlogBundle:Page:about }
  requirements:
    _method: GET
    
BloggerBlogBundle_contact:    
  pattern: /contact
  defaults: { _controller: BloggerBlogBundle:Page:contact }
  requirements:
    _method: get|post
    
BloggerBlogBundle_blog_show:    
  pattern: /{id}
  defaults: { _controller: BloggerBlogBundle:Blog:show }
  requirements:
    _method: get
    id: \d+
    
BloggerBlogBundle_comment_create:
  pattern: /comment/{blog_id}
  defaults: { _controller: BloggerBlogBundle:Comment:create }
  requirements:
    _method: post
    blog_id: \d+